### ISSUE TITLE
Deployment of an Ember app fails with EPERM issues

### ISSUE THREAD

**Issue by mfcollins3** [felixrieseberg/ember-cli-azure-deploy#18]
I'm trying to deploy an Ember app using ember-cli-azure-deploy. I've followed the instructions, but I have yet to get a successful deployment. I've seen connection issues and segmentation faults with NPM, but the latest error that I am getting is this:

Error: EPERM: operation not permitted, symlink 'D:\local\Temp\8d3d8e71a615f23\app' -> 'D:\local\Temp\8d3d8e71a615f23\tmp\funnel-input_base_path-vsGMDdb9.tmp\0'

I have attached the build log. I'm trying to deploy to a website running on a Basic 2 VM (2 CPUs, 3.5GB RAM).

Any ideas of what I can try?

[RD00155DD0B70F-3cdb92c4-00a9-47da-ba6c-54f44a438a79.txt](https://github.com/felixrieseberg/ember-cli-azure-deploy/files/464695/RD00155DD0B70F-3cdb92c4-00a9-47da-ba6c-54f44a438a79.txt)

**Comment by dougajmcdonald** [comment]
I'm seeing the same kind of thing, will let you know if I find a solution

**Comment by graham-sportsmgmt** [comment]
Add me to the list of people who are seeing this error.  I'm using continuous deployment from Visual Studio Online.  A manual copy of the build from my local machine (Win 10) via FTP works perfectly.  Some posts on StackOverflow indicate that this might be a permissions issue, can we elevate to an administrator inside Azure?

This was the first error in my log:

The Broccoli Plugin: [Funnel: Funnel: index.html] failed with:
Build failed.
Error: EPERM: operation not permitted, symlink 'D:\local\Temp\8d3f07740bebaf5\app' -> 'D:\local\Temp\8d3f07740bebaf5\tmp\funnel-input_base_path-oLs8EZQa.tmp\0'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
Copy web.config to the dist folder
    at symlinkWindows (D:\local\Temp\8d3f07740bebaf5\node_modules\symlink-or-copy\index.js:104:18)
    at symlinkOrCopySync (D:\local\Temp\8d3f07740bebaf5\node_modules\symlink-or-copy\index.js:53:5)
    at D:\local\Temp\8d3f07740bebaf5\node_modules\broccoli-plugin\read_compat.js:58:9
    at tryCatch (D:\local\Temp\8d3f07740bebaf5\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (D:\local\Temp\8d3f07740bebaf5\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (D:\local\Temp\8d3f07740bebaf5\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (D:\local\Temp\8d3f07740bebaf5\node_modules\rsvp\dist\rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:420:9)

**Comment by dougajmcdonald** [comment]
I think you're right on the administrator issue as a potential cause, but I can run the same command locally as a non-administrator, so probably more something which Azure locks down.

**Comment by powerchelle** [comment]
Hi, I'm seeing the same issue.  Anyone made headway on this?

Build the dist folder
Executing "ember build -prod". This might take a while.

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Build failed.
The Broccoli Plugin: [Funnel: Funnel: index.html] failed with:
Error: EPERM: operation not permitted, symlink 'D:\local\Temp\8d421e839a0f299\app' -> 'D:\local\Temp\8d421e839a0f299\tmp\funnel-input_base_path-uPMtwHHB.tmp'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:902:18)
Copy web.config to the dist folder
    at symlinkWindows (D:\local\Temp\8d421e839a0f299\node_modules\symlink-or-copy\index.js:123:18)
    at symlinkOrCopySync (D:\local\Temp\8d421e839a0f299\node_modules\symlink-or-copy\index.js:63:5)
    at D:\local\Temp\8d421e839a0f299\node_modules\broccoli-plugin\read_compat.js:86:11
    at tryCatch (D:\local\Temp\8d421e839a0f299\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (D:\local\Temp\8d421e839a0f299\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (D:\local\Temp\8d421e839a0f299\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (D:\local\Temp\8d421e839a0f299\node_modules\rsvp\dist\rsvp.js:2373:5)
    at doNTCallback0 (node.js:408:9)

**Comment by ahlivehr** [comment]
I'm also experiencing this issue. Has anyone found a solution to this issue yet?

**Comment by graham-sportsmgmt** [comment]
I'm now manually building and deploying without this plugin.

**Comment by ahlivehr** [comment]
@graham-sportsmgmt Is there a tutorial you followed that might be helpful for manually deploying your Ember app to Azure? I'm still stuck on how to manually deploy to Azure. Are you using FTP, GIT, or something else to deploy your app?

**Comment by graham-sportsmgmt** [comment]
The node.js deployment from TFS/VSTS works great, so I'm just issuing a local build command then copying the files from the resulting /dist folder to the /public directory in my node/express server.  I push that into VSTS and it works well.
