### ISSUE TITLE
ReferenceError: namespae is not defined

### ISSUE THREAD

**Issue by graham-sportsmgmt** [felixrieseberg/ember-cli-azure-deploy#21]
I just got the following build error (namespae is not defined) when using v1.4.1 of the tool.

> Using Node v0.12.6
> Using npm 3.3.9
> Using bower 1.8.0
> Using ember-cli-azure-deploy 1.4.1

I'm not sure why it's using Node v0.12.6, I have specified 6.9.0 in package.json and WEBSITE_NODE_DEFAULT_VERSION.

```
ReferenceError: namespae is not defined
Copy web.config to the dist folder
    at createDebug (D:\local\Temp\8d423eef86d8b26\node_modules\debug\debug.js:126:29)
    at Object.<anonymous> (D:\local\Temp\8d423eef86d8b26\node_modules\leek\lib\provider.js:3:29)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\local\Temp\8d423eef86d8b26\node_modules\leek\lib\leek.js:5:19)
    at Module._compile (module.js:435:26)
{ [Error: Command failed: D:\Windows\system32\cmd.exe /s /c "node D:\local\Temp\8d423eef86d8b26\node_modules\ember-cli\bin\ember build -prod"
D:\local\Temp\8d423eef86d8b26\node_modules\debug\debug.js:126
  debug.color = selectColor(namespae);
                            ^

```

**Comment by graham-sportsmgmt** [comment]
Unable to reproduce.
